[tool.poetry]
name = "credit-score-prediction"
version = "0.1.0"
description = "An end-to-end example of how to apply software engineering practices for ML training, testing and deployment"
authors = ["David Tan <davidtan@thoughtworks.com>"]
packages = [{include = "training", from = "src"}]

[tool.poetry.dependencies]
pandas = "1.5.1"
scikit-learn = "1.2.2"
fastapi = "0.85.2"
pydantic = "1.10.6"
uvicorn = "0.21.1"
python = "^3.9"

[tool.poetry.dev-dependencies]
jupyter = "1.0.0"
black = "23.1.0"
pylint = "^2.17.0"
precisely = "^0.1.9"
pytest = "^7.2.2"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"