[tool.poetry]
name = "loan-default-prediction"
version = "0.1.0"
description = "An end-to-end example of how to apply software engineering practices for ML training, testing and deployment"
authors = ["David Tan <davidtan@thoughtworks.com>"]
packages = [{include = "training", from = "src"}]

[tool.poetry.dependencies]
pandas = "2.2.2"
scikit-learn = "1.4.2"
fastapi = "0.110.1"
pydantic = "2.6.4"
uvicorn = "0.29.0"
python = "^3.9"
httpx = "^0.27.0"

[tool.poetry.dev-dependencies]
jupyter = "1.0.0"
black = "24.4.0"
pylint = "^3.1.0"
precisely = "^0.1.9"
pytest = "^8.1.1"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"