[tool.poetry]
name = "credit-score-prediction"
version = "0.1.0"
description = "An end-to-end example of how to apply software engineering practices for ML training, testing and deployment"
authors = ["David Tan <davidtan@thoughtworks.com>"]
packages = [{include = "training", from = "src"}]

[tool.poetry.dependencies]
pandas = "2.1.3"
scikit-learn = "1.3.2"
fastapi = "0.104.1"
pydantic = "2.5.2"
uvicorn = "0.24.0.post1"
python = "^3.9"
httpx = "^0.25.2"

[tool.poetry.dev-dependencies]
jupyter = "1.0.0"
black = "23.11.0"
pylint = "^3.0.2"
precisely = "^0.1.9"
pytest = "^7.4.3"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"