[tool.poetry]
name = "loan-default-prediction"
version = "0.1.0"
description = "An end-to-end example of how to apply software engineering practices for ML training, testing and deployment"
authors = ["David Tan <davidtan@thoughtworks.com>"]
packages = [{include = "training", from = "src"}]

[tool.poetry.dependencies]
pandas = "2.2.0"
scikit-learn = "1.4.1.post1"
fastapi = "0.109.2"
pydantic = "2.6.2"
uvicorn = "0.27.1"
python = "^3.9"
httpx = "^0.27.0"

[tool.poetry.dev-dependencies]
jupyter = "1.0.0"
black = "24.2.0"
pylint = "^3.0.3"
precisely = "^0.1.9"
pytest = "^8.0.1"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"